const products = [
    {
        id: 0,
        name: "Mini Kebab",
        description: "fileu de pui, lavaș, roșii, sos, morcov corean, varză proaspătă, cartofi pai, castraveți murați",
        price: 25,
        imgSrc:"../images/kebab/kebab3.png",
        hide: "hide1()",
        show: "show1()",
        info: "info-container-1",
        shop: "shop-container-1",
    },
    {
        id: 1,
        name: "Kebab Pui",
        description: "fileu de pui, lavaș, roșii, sos, morcov corean, varză proaspătă, cartofi pai, castraveți murați",
        price: 45,
        imgSrc:"../images/kebab/kebab1.png",
        hide: "hide2()",
        show: "show2()",
        info: "info-container-2",
        shop: "shop-container-2",
    },
    {
        id: 2,
        name: "Kebab Porc",
        description: "burtă de porc, lavaș, roșii, sos, morcov corean, varză proaspătă, castraveți murați, cartofi pai",
        price: 50,
        imgSrc:"../images/kebab/kebab2.png",
        hide: "hide3()",
        show: "show3()",
        info: "info-container-3",
        shop: "shop-container-3",
    },
    {
        id: 3,
        name: "Mega Kebab",
        description: "fileu de pui dublu, lavaș, roșii, becon, varză proaspătp, castraveți murați, cașcaval",
        price: 55,
        imgSrc:"../images/kebab/kebab4.png",
        hide: "hide4()",
        show: "show4()",
        info: "info-container-4",
        shop: "shop-container-4",
    },
]